[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
topcoat = { version = "0.10.0", features = ["asset", "fs", "runtime", "websocket", "asset", "compression", "tailwind", "font-fontsource"] }
tokio = { version = "1.53.2", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.13.5", features = ["json"], default-features = false }

[build-dependencies]
topcoat = { version = "0.10.0", default-features = false, features = ["tailwind"] }