[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.53.2", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.13.5", features = ["json"], default-features = false }
tower = "0.5.3"
tower-http = { version = "0.7.1", features = ["fs", "cors","compression-gzip"] }
topcoat = { version = "0.10.0", features = ["asset", "fs", "runtime", "websocket", "compression", "tailwind", "font-fontsource", "tower"] }

[build-dependencies]
topcoat = { version = "0.10.0", default-features = false, features = ["tailwind"] }
reqwest = { version = "0.13.5", default-features = false, features = ["blocking", "rustls"] }
flate2 = "1.1.10"
brotli = "9.0.0"
